version: '3.1'
services:
  fastapi:
    image: fastapi-cours
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: cours
    networks:
      - backend
    ports:
      - 5432:5432

networks:
  backend:
